name: stopwordies
description: A multilingual collection of stopwords (using ISO 639-1 language codes) for Dart/Flutter.
version: 1.0.1
homepage: https://github.com/maranathApp/stopwordies
repository: https://github.com/maranathApp/stopwordies
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/jsons/

